import type { Metadata } from "next";
import { Geist, Geist_Mono, PT_Serif, Oswald } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const oswald = Oswald({
    variable: "--font-oswald",
    weight: ["200", '300', '400', '500', '600', '700'],
    subsets: ['cyrillic']
})

const ptSerif = PT_Serif({
    variable: "--font-pt-serif",
    weight: ["400", "700"],
    subsets: ['cyrillic']
})

const gothic = localFont({
    src: 'fonts/goth.woff2',
    variable: '--font-gothic'
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${ptSerif.variable} ${oswald.variable} ${gothic.variable} antialiased dark`}
            >
                {children}
            </body>
        </html>
    );
}
